package sec02.exam04;

public class CatchByExceptionKindExample {

	public static void main(String[] args) {
		String data1 = null;
		String data2 = null;

		try {
			//ArrayIndexOutOfBoundsException 발생가능
			data1 = args[0];
			data2 = args[1];
	
			//NumberFormatException 발생가능
			int value1 = Integer.parseInt(data1);
			int value2 = Integer.parseInt(data2);
			int result = value1 + value2;
	
			System.out.println(data1 + "+" + data2 + "=" + result);
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("실행 매개값의 수가 부족합니다.");
		} catch (NumberFormatException e) {
			System.out.println("숫자로 변환할 수 없습니다.");
		} catch (Exception e) {
			//위 catch문에서 잡지못한 모든 오류를 Exception 처리함
			System.out.println("오류가 발생하였습니다.");
		}finally {
			System.out.println("다시 실행하세요.");
		}
	}
}
